#include <softberg/utils.h>

#include <stdio.h>
#include <errno.h>



int sb_write_ppm(sb_canvas *canvas, const char * restrict filepath) {
  FILE *file = fopen(filepath, "w");
  if (!file) return ENOENT;

  fprintf(file, "P3\n# Generated by github.com/lucilands/softberg\n%i %i\n255\n", canvas->width, canvas->height);
  for (sb_uint i = 0; i < canvas->width * canvas->height; i++) {
    sb_color pixel = canvas->data[i];
    fprintf(file, "%i %i %i\n", pixel.r, pixel.g, pixel.b);
  }

  return 0;
}

int sb_write_depth_ppm(sb_canvas *canvas, const char * restrict filepath) {
  FILE *file = fopen(filepath, "w");
  if (!file) return ENOENT;

  fprintf(file, "P3\n# Generated by github.com/lucilands/softberg\n%i %i\n255\n", canvas->width, canvas->height);
  for (sb_uint i = 0; i < canvas->width * canvas->height; i++) {
    float pixel = canvas->depth[i];
    fprintf(file, "%i %i %i\n", (int)pixel * 255, (int)pixel * 255, (int)pixel * 255);
  }

  return 0;
}

